name: paper
dependencies:
- anaconda-client=1.1.2=py35_0
- clyent=1.0.0=py35_0
- decorator=4.0.4=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- geos=3.3.3=0
- ipython=4.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- jbig=2.1=0
- jpeg=8d=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- matplotlib=1.4.3=np110py35_2
- networkx=1.10=py35_0
- numpy=1.10.1=py35_0
- openblas=0.2.14=3
- openssl=1.0.2g=0
- palettable=2.1.1=py35_0
- pandas=0.17.0=np110py35_0
- path.py=8.1.2=py35_0
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pillow=3.0.0=py35_1
- pip=8.1.0=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- qt=4.8.7=1
- readline=6.2=2
- requests=2.8.1=py35_0
- scipy=0.16.0=np110py35_1
- seaborn=0.6.0=np110py35_0
- setuptools=20.2.2=py35_0
- shapely=1.5.11=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- traitlets=4.0.0=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - bctpy==0.5.0
  - cairocffi==0.7.2
  - connectome-utils==0.0.0
  - cycler==0.9.0
  - distance==0.1.3
  - hiveplotter==0.1
  - ipython-genutils==0.1.0
  - progressbar2==3.6.0
  - ptyprocess==0.5
  - pycparser==2.14
  - python-pushover==0.2
  - pyx==0.14.1
  - virtualenv==13.1.2

